{
 "title": "Nomad Autoscaler Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_memory_used)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_total)"
    }
   ]
  },
  {
   "title": "Client memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "nomad_client_host_memory_total", "legendFormat": "total" },
    {
     "expr": "nomad_client_allocated_memory*(1024*1024)",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_usage) by (instance)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Client CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_client_host_cpu_total", "legendFormat": "{{cpu}}" }
   ]
  },
  {
   "title": "wordpress-app group count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"demo\"}",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Avg. connections/instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_usage{exported_job=\"wordpress-app\"})/1000000"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_usage{exported_job=\"wordpress-app\"})/1000000",
     "legendFormat": "avg"
    },
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"demo\"}",
     "legendFormat": "count"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_usage{exported_job=\"wordpress-app\"})/1000000",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Traefik Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"traefik\",task=\"server\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"traefik\",task=\"server\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Nomad Autoscaler Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"autoscaler\",task=\"autoscaler\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"autoscaler\",task=\"autoscaler\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "wordpress-app Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"demo\",task=\"wordpress-app\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"demo\",task=\"wordpress-app\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Toxiproxy Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"demo\",task=\"toxiproxy\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"demo\",task=\"toxiproxy\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Prometheus Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"prometheus\",task=\"prometheus\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"prometheus\",task=\"prometheus\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Grafana Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"grafana\",task=\"grafana\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"grafana\",task=\"grafana\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Loki Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"loki\",task=\"loki\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"loki\",task=\"loki\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Promtail Mem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"autoscaler\",task=\"promtail\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"autoscaler\",task=\"promtail\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}